name: CI

on:
  push:
    branches: [master, 'dev/**']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: PHP 8.4

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, json, libxml, zip
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - run: vendor/bin/pint --test --parallel
      - run: vendor/bin/phpstan analyse --no-progress
      - run: vendor/bin/pest --ci --exclude-group=anaf-test
